apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulntracker.fullname" . }}
  labels:
    app: vulntracker

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: vulntracker

  template:
    metadata:
      labels:
        app: vulntracker

    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}

      containers:
        - name: vulntracker

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
{{ toYaml .Values.securityContext.capabilities.drop | indent 16 }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SECRET_KEY

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_PASSWORD

          resources:
{{ toYaml .Values.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30