apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vulntracker.fullname" . }}
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app: vulntracker

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - ports:
        - protocol: TCP
          port: 8000

  egress:
    # Allow DNS resolution
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow HTTPS access for external services such as AWS APIs
    - ports:
        - protocol: TCP
          port: 443