apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulntracker.fullname" . }}
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: vulntracker

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP