replicaCount: 2

image:
  repository: vulntracker-app
  tag: task4
  digest: "sha256:023b5d691bc25c3ba710579a9fc3fb121fd21fdb069e9cf546f22840d1b9c53b"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

namespace: vulntracker

ingress:
  enabled: true
  className: alb
  host: vulntracker.example.com
  path: /
  pathType: Prefix
  internal: true
  allowedCidrs:
    - 10.0.0.0/8

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

secretStore:
  name: aws-secretsmanager
  kind: ClusterSecretStore

secret:
  name: vulntracker-secrets
  remoteKey: vulntracker/production